"""Changed employee status name to unique

Revision ID: 0a48b65aa751
Revises: 3df266d8f883
Create Date: 2025-12-19 13:00:36.518960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a48b65aa751'
down_revision: Union[str, Sequence[str], None] = '3df266d8f883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'employee_status', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_status', type_='unique')
    # ### end Alembic commands ###
