"""update column is_active in department and job table

Revision ID: 77cb6d983711
Revises: 0a48b65aa751
Create Date: 2025-12-30 14:26:50.288646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cb6d983711'
down_revision: Union[str, Sequence[str], None] = '0a48b65aa751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('employee_status', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('job', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'is_active')
    op.drop_column('employee_status', 'is_active')
    op.drop_column('department', 'is_active')
    # ### end Alembic commands ###
