"""add email address on employee table

Revision ID: cc8fddb2bae9
Revises: 77cb6d983711
Create Date: 2026-01-19 00:33:47.249792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8fddb2bae9'
down_revision: Union[str, Sequence[str], None] = '77cb6d983711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email_address', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'employee', ['email_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'email_address')
    # ### end Alembic commands ###
