"""change employee column departmen to department_id

Revision ID: e033941ba052
Revises: cc8fddb2bae9
Create Date: 2026-01-20 20:39:26.837594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e033941ba052'
down_revision: Union[str, Sequence[str], None] = 'cc8fddb2bae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('employee_ibfk_1'), 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['id'])
    op.drop_column('employee', 'departmen_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('departmen_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key(op.f('employee_ibfk_1'), 'employee', 'department', ['departmen_id'], ['id'])
    op.drop_column('employee', 'department_id')
    # ### end Alembic commands ###
